### ISSUE TITLE
Logins stopped working overnight

### ISSUE THREAD

**Issue by Andicraft** [valknight/Cohost.py#9]
My code was working just fine last night, but today I'm getting some fun errors:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cohost/network.py", line 48, in fetch
    res = req.json()
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/cohostbot/bot.py", line 73, in <module>
    main()
  File "/root/cohostbot/bot.py", line 56, in main
    user = User.login(username, password)
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cohost/models/user.py", line 89, in login
    salt = fetch("GET", "/login/salt", {"email": email})['salt']
  File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cohost/network.py", line 50, in fetch
    res = req.text()
TypeError: 'str' object is not callable
```

Here's the relevant code (with username and email stripped out). It worked fine last night and then stopped working without any changes.
```
        username = 'SECRET'
        password = 'NOTFORYOU'
        handle = 'StreetViewBot'
        user = User.login(username, password)
        project = user.getProject(handle)
        blocks = [
                AttachmentBlock('streetview_image/gsv_0.jpg'),
                MarkdownBlock('<div style="text-align: center; font-weight: bold;">'),
                MarkdownBlock(location.address),
                MarkdownBlock('</div>')
        ]
        tags = [
                'street view',
                'maps',
                location.raw['address']['country']
        ]
        newPost = project.post('', blocks,tags)
        print(f'Posted to {newPost.url}')
```

**Comment by Vildravn** [comment]
From what I can tell, cohost is now using cloudflare and "Checking if the site connection is secure" which is blocking any calls as it's checking for javascript and some cookies, and potentially has a recaptcha.

**Comment by valknight** [comment]
hm, thats super interesting ! it looks like for whatever reason cohost isn't sending json back.

i am aware cohost had an outage last night so i'm curious if this is related. i'll need to add retrying to our network stuff

for now though: i think route forward is ensuring we actually log whatever cohost spits out here - i'll see if i can find some time after work to take a look at doing this

**Comment by asoftbird** [comment]
Got the same error; last succesful execution of my bot occured at 3am UTC, so whatever changed likely occured somewhere between 3 and 4am UTC.

**Comment by valknight** [comment]
fixed for now! cohost seems to have implemented anti spam measures overnight, but actually setting our user agent to "cohost.py" fixes this 😄

**Comment by valknight** [comment]
(release out later today!)

**Comment by valknight** [comment]
i'll do a fancy release note later, but, for now - this is fixed, and the package is now avaliable for download - upgrade with `pip install --upgrade cohost`
